# Generated by Django 4.2.3 on 2023-07-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "premise_id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("postal_code", models.DecimalField(decimal_places=0, max_digits=6)),
                ("total_population", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("movement_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=15)),
                ("shipment_start_date", models.DateField()),
                ("items_moved", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=50)),
                (
                    "dest_premise_id",
                    models.ForeignKey(
                        db_column="dest_premise_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dest_premise_id",
                        to="farm_movement.farm",
                    ),
                ),
                (
                    "origin_premise_id",
                    models.ForeignKey(
                        db_column="origin_premise_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_premise_id",
                        to="farm_movement.farm",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(
                fields=(
                    "company",
                    "origin_premise_id",
                    "dest_premise_id",
                    "species",
                    "shipment_start_date",
                ),
                name="unique movement key",
            ),
        ),
    ]
